# Use an official Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy files into container
COPY app.py .
COPY model.pkl .
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Expose port 5000
EXPOSE 5000

# Run the Flask app
CMD ["python", "app.py"]
